[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "utils"
version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]
name = "utils"

[dependencies]
parking_lot = { workspace = true }
web-time = { workspace = true }
