[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "utils"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "utils"

[dependencies]
web-time = { workspace = true }
