[package]
edition.workspace = true
name = "ui-proc"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
parking_lot = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
