imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_strings = true
struct_field_align_threshold = 100
use_field_init_shorthand = true
wrap_comments = true
max_width = 110
chain_width = 80
brace_style = "PreferSameLine"
where_single_line = true