[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "ui"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
doctest = false
name = "ui"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
derivative = { workspace = true }
dispatch = { workspace = true }
fake = { workspace = true }
itertools = { workspace = true }
nonempty = { workspace = true }
reflected = { workspace = true }
refs = { workspace = true }
rust_decimal = { workspace = true }
tokio = { workspace = true }
vents = { workspace = true }
wgpu_wrapper = { workspace = true }

gm = { workspace = true }
ui_proc = { workspace = true }


[build-dependencies]
cfg_aliases = { workspace = true }
