[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "ui"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
doctest = false
name = "ui"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
convert_case = { workspace = true }
dispatch = { workspace = true }
educe = { workspace = true }
fake = { workspace = true }
log = { workspace = true }
manage = { workspace = true }
nonempty = { workspace = true }
reflected = { workspace = true }
refs = { workspace = true }
rust_decimal = { workspace = true }
tokio = { workspace = true }
utils = { workspace = true }
vents = { workspace = true }
wgpu-wrapper = { workspace = true }

gm = { workspace = true }
ui-proc = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
