[package]
edition.workspace = true
name = "filesystem"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
plat = { workspace = true }

[target.'cfg(not(target_os = "ios"))'.dependencies]
rfd = { workspace = true }

[build-dependencies]
plat = { workspace = true }
