[package]
edition = "2021"
name = "valid"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
strum_macros = "0.24"

reflected = { workspace = true }
reflected_proc = { workspace = true }
