[package]
edition.workspace = true
name = "inspect"
version.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
plat = { workspace = true }
