[package]
edition.workspace = true
name = "inspect"
version.workspace = true

[dependencies]
serde = { workspace = true }

netrun = { workspace = true }

gm = { workspace = true }
ui = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
plat = { workspace = true }
