[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "level"

[lib]
crate-type = ["rlib", "staticlib"]
name = "level"

[dependencies]
educe = { workspace = true }
rapier2d = { workspace = true }

gm = { workspace = true }
level-proc = { workspace = true }
refs = { workspace = true }
utils = { workspace = true }
vents = { workspace = true }
window = { workspace = true }
